spring:
  application:
    name: PubSubApplication
  cloud:
    gcp:
      project-id: ${SPRING_CLOUD_GCP_PROJECT_ID:learningpurpose-492409}
      credentials:
        location: ${GCP_CREDENTIALS:file:C:\Users\loges\Downloads\PubSubApplication\service1\gcp-key.json}
      pubsub:
        enabled: true