name: Production CI-CD

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Sender
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sender-service ./service1
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sender-service

      - name: Deploy Sender to Cloud Run
        run: |
          gcloud run deploy sender-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/sender-service \
            --region us-central1 \
            --allow-unauthenticated

      - name: Build and Push Receiver
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/receiver-service ./service2
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/receiver-service

      - name: Deploy Receiver to Cloud Run
        run: |
          gcloud run deploy receiver-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/receiver-service \
            --region us-central1 \
            --allow-unauthenticated